history_tag: My App
sesame:
  api_key: <Your API Key>
  secret_key: <Your Secret Key>
  uuid: <Your Device UUID>
slack:
  signing_secret: <Your Slack Signing Secret>
gcp:
  project_id: <Your project ID>
  topic: <Your topic>