"""
This type stub file was generated by pyright.
"""

import abc
from typing import Awaitable, Callable, Optional, Sequence, Union
from google.api_core import gapic_v1
from google.auth import credentials as ga_credentials
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.protobuf import empty_pb2
from google.pubsub_v1.types import schema

class SchemaServiceTransport(abc.ABC):
    """Abstract transport class for SchemaService."""
    AUTH_SCOPES = ...
    DEFAULT_HOST: str = ...
    def __init__(self, *, host: str = ..., credentials: ga_credentials.Credentials = ..., credentials_file: Optional[str] = ..., scopes: Optional[Sequence[str]] = ..., quota_project_id: Optional[str] = ..., client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: Optional[bool] = ..., **kwargs) -> None:
        """Instantiate the transport.

        Args:
            host (Optional[str]):
                 The hostname to connect to.
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            credentials_file (Optional[str]): A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`.
                This argument is mutually exclusive with credentials.
            scopes (Optional[Sequence[str]]): A list of scopes.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you're developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.
        """
        ...
    
    def close(self):
        """Closes resources associated with the transport.

        .. warning::
             Only call this method if the transport is NOT shared
             with other clients - this may cause errors in other clients!
        """
        ...
    
    @property
    def create_schema(self) -> Callable[[gp_schema.CreateSchemaRequest], Union[gp_schema.Schema, Awaitable[gp_schema.Schema]],]:
        ...
    
    @property
    def get_schema(self) -> Callable[[schema.GetSchemaRequest], Union[schema.Schema, Awaitable[schema.Schema]]]:
        ...
    
    @property
    def list_schemas(self) -> Callable[[schema.ListSchemasRequest], Union[schema.ListSchemasResponse, Awaitable[schema.ListSchemasResponse]],]:
        ...
    
    @property
    def delete_schema(self) -> Callable[[schema.DeleteSchemaRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]]]:
        ...
    
    @property
    def validate_schema(self) -> Callable[[gp_schema.ValidateSchemaRequest], Union[gp_schema.ValidateSchemaResponse, Awaitable[gp_schema.ValidateSchemaResponse],],]:
        ...
    
    @property
    def validate_message(self) -> Callable[[schema.ValidateMessageRequest], Union[schema.ValidateMessageResponse, Awaitable[schema.ValidateMessageResponse]],]:
        ...
    
    @property
    def set_iam_policy(self) -> Callable[[iam_policy_pb2.SetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def get_iam_policy(self) -> Callable[[iam_policy_pb2.GetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def test_iam_permissions(self) -> Callable[[iam_policy_pb2.TestIamPermissionsRequest], Union[iam_policy_pb2.TestIamPermissionsResponse, Awaitable[iam_policy_pb2.TestIamPermissionsResponse],],]:
        ...
    
    @property
    def kind(self) -> str:
        ...
    


__all__ = ("SchemaServiceTransport", )
