"""
This type stub file was generated by pyright.
"""

"""AsyncIO helpers for wrapping gRPC methods with common functionality.

This is used by gapic clients to provide common error mapping, retry, timeout,
pagination, and long-running operations to gRPC methods.
"""
def wrap_method(func, default_retry=..., default_timeout=..., client_info=...): # -> _GapicCallable:
    """Wrap an async RPC method with common behavior.

    Returns:
        Callable: A new callable that takes optional ``retry`` and ``timeout``
            arguments and applies the common error mapping, retry, timeout,
            and metadata behavior to the low-level RPC method.
    """
    ...

