"""
This type stub file was generated by pyright.
"""

import abc
from typing import Awaitable, Callable, Optional, Sequence, Union
from google.api_core import gapic_v1
from google.auth import credentials as ga_credentials
from google.iam.v1 import iam_policy_pb2, policy_pb2
from google.protobuf import empty_pb2
from google.pubsub_v1.types import pubsub

class SubscriberTransport(abc.ABC):
    """Abstract transport class for Subscriber."""
    AUTH_SCOPES = ...
    DEFAULT_HOST: str = ...
    def __init__(self, *, host: str = ..., credentials: ga_credentials.Credentials = ..., credentials_file: Optional[str] = ..., scopes: Optional[Sequence[str]] = ..., quota_project_id: Optional[str] = ..., client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: Optional[bool] = ..., **kwargs) -> None:
        """Instantiate the transport.

        Args:
            host (Optional[str]):
                 The hostname to connect to.
            credentials (Optional[google.auth.credentials.Credentials]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            credentials_file (Optional[str]): A file with credentials that can
                be loaded with :func:`google.auth.load_credentials_from_file`.
                This argument is mutually exclusive with credentials.
            scopes (Optional[Sequence[str]]): A list of scopes.
            quota_project_id (Optional[str]): An optional project to use for billing
                and quota.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you're developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.
        """
        ...
    
    def close(self):
        """Closes resources associated with the transport.

        .. warning::
             Only call this method if the transport is NOT shared
             with other clients - this may cause errors in other clients!
        """
        ...
    
    @property
    def create_subscription(self) -> Callable[[pubsub.Subscription], Union[pubsub.Subscription, Awaitable[pubsub.Subscription]],]:
        ...
    
    @property
    def get_subscription(self) -> Callable[[pubsub.GetSubscriptionRequest], Union[pubsub.Subscription, Awaitable[pubsub.Subscription]],]:
        ...
    
    @property
    def update_subscription(self) -> Callable[[pubsub.UpdateSubscriptionRequest], Union[pubsub.Subscription, Awaitable[pubsub.Subscription]],]:
        ...
    
    @property
    def list_subscriptions(self) -> Callable[[pubsub.ListSubscriptionsRequest], Union[pubsub.ListSubscriptionsResponse, Awaitable[pubsub.ListSubscriptionsResponse],],]:
        ...
    
    @property
    def delete_subscription(self) -> Callable[[pubsub.DeleteSubscriptionRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def modify_ack_deadline(self) -> Callable[[pubsub.ModifyAckDeadlineRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def acknowledge(self) -> Callable[[pubsub.AcknowledgeRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]]]:
        ...
    
    @property
    def pull(self) -> Callable[[pubsub.PullRequest], Union[pubsub.PullResponse, Awaitable[pubsub.PullResponse]]]:
        ...
    
    @property
    def streaming_pull(self) -> Callable[[pubsub.StreamingPullRequest], Union[pubsub.StreamingPullResponse, Awaitable[pubsub.StreamingPullResponse]],]:
        ...
    
    @property
    def modify_push_config(self) -> Callable[[pubsub.ModifyPushConfigRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def get_snapshot(self) -> Callable[[pubsub.GetSnapshotRequest], Union[pubsub.Snapshot, Awaitable[pubsub.Snapshot]]]:
        ...
    
    @property
    def list_snapshots(self) -> Callable[[pubsub.ListSnapshotsRequest], Union[pubsub.ListSnapshotsResponse, Awaitable[pubsub.ListSnapshotsResponse]],]:
        ...
    
    @property
    def create_snapshot(self) -> Callable[[pubsub.CreateSnapshotRequest], Union[pubsub.Snapshot, Awaitable[pubsub.Snapshot]],]:
        ...
    
    @property
    def update_snapshot(self) -> Callable[[pubsub.UpdateSnapshotRequest], Union[pubsub.Snapshot, Awaitable[pubsub.Snapshot]],]:
        ...
    
    @property
    def delete_snapshot(self) -> Callable[[pubsub.DeleteSnapshotRequest], Union[empty_pb2.Empty, Awaitable[empty_pb2.Empty]],]:
        ...
    
    @property
    def seek(self) -> Callable[[pubsub.SeekRequest], Union[pubsub.SeekResponse, Awaitable[pubsub.SeekResponse]]]:
        ...
    
    @property
    def set_iam_policy(self) -> Callable[[iam_policy_pb2.SetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def get_iam_policy(self) -> Callable[[iam_policy_pb2.GetIamPolicyRequest], Union[policy_pb2.Policy, Awaitable[policy_pb2.Policy]],]:
        ...
    
    @property
    def test_iam_permissions(self) -> Callable[[iam_policy_pb2.TestIamPermissionsRequest], Union[iam_policy_pb2.TestIamPermissionsResponse, Awaitable[iam_policy_pb2.TestIamPermissionsResponse],],]:
        ...
    
    @property
    def kind(self) -> str:
        ...
    


__all__ = ("SubscriberTransport", )
