"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from google.cloud.pubsub_v1 import publisher, subscriber, types
from google.pubsub_v1.services import schema_service

class PublisherClient(publisher.Client):
    __doc__ = ...


class SubscriberClient(subscriber.Client):
    __doc__ = ...


class SchemaServiceClient(schema_service.client.SchemaServiceClient):
    __doc__ = ...


__all__ = ("types", "PublisherClient", "SubscriberClient", "SchemaServiceClient")
