"""
This type stub file was generated by pyright.
"""

from typing import Type
from google.cloud.pubsub_v1 import types

_LOGGER = ...
MessageType = Type[types.PubsubMessage]
class _QuantityReservation:
    """A (partial) reservation of quantifiable resources."""
    def __init__(self, bytes_reserved: int, bytes_needed: int, has_slot: bool) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class FlowController:
    """A class used to control the flow of messages passing through it.

    Args:
        settings: Desired flow control configuration.
    """
    def __init__(self, settings: types.PublishFlowControl) -> None:
        ...
    
    def add(self, message: MessageType) -> None:
        """Add a message to flow control.

        Adding a message updates the internal load statistics, and an action is
        taken if these limits are exceeded (depending on the flow control settings).

        Args:
            message:
                The message entering the flow control.

        Raises:
            :exception:`~pubsub_v1.publisher.exceptions.FlowControlLimitError`:
                Raised when the desired action is
                :attr:`~google.cloud.pubsub_v1.types.LimitExceededBehavior.ERROR` and
                the message would exceed flow control limits, or when the desired action
                is :attr:`~google.cloud.pubsub_v1.types.LimitExceededBehavior.BLOCK` and
                the message would block forever against the flow control limits.
        """
        ...
    
    def release(self, message: MessageType) -> None:
        """Release a mesage from flow control.

        Args:
            message:
                The message entering the flow control.
        """
        ...
    


