"""
This type stub file was generated by pyright.
"""

import typing
from google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager import StreamingPullManager

if typing.TYPE_CHECKING:
    ...
_LOGGER = ...
_HEARTBEAT_WORKER_NAME = ...
_DEFAULT_PERIOD = ...
class Heartbeater:
    def __init__(self, manager: StreamingPullManager, period: int = ...) -> None:
        ...
    
    def heartbeat(self) -> None:
        """Periodically send streaming pull heartbeats."""
        ...
    
    def start(self) -> None:
        ...
    
    def stop(self) -> None:
        ...
    


