"""
This type stub file was generated by pyright.
"""

import typing
from typing import NamedTuple, Optional
from google.cloud.pubsub_v1.subscriber import futures

if typing.TYPE_CHECKING:
    ...
class AckRequest(NamedTuple):
    ack_id: str
    byte_size: int
    time_to_ack: float
    ordering_key: Optional[str]
    future: Optional[futures.Future]
    ...


class DropRequest(NamedTuple):
    ack_id: str
    byte_size: int
    ordering_key: Optional[str]
    ...


class LeaseRequest(NamedTuple):
    ack_id: str
    byte_size: int
    ordering_key: Optional[str]
    ...


class ModAckRequest(NamedTuple):
    ack_id: str
    seconds: float
    future: Optional[futures.Future]
    ...


class NackRequest(NamedTuple):
    ack_id: str
    byte_size: int
    ordering_key: Optional[str]
    future: Optional[futures.Future]
    ...


